FROM mcr.microsoft.com/dotnet/core/sdk:3.1
ENV project Parser

COPY CalendarBackendLib /app/CalendarBackendLib

WORKDIR /app/${project}

COPY ${project}/${project}.csproj ./
RUN dotnet restore

COPY ${project}/ ./
RUN dotnet publish -c Release -o /app/out


FROM mcr.microsoft.com/dotnet/core/runtime:3.1-alpine
WORKDIR /app
VOLUME /app/calendars
VOLUME /app/eventfiles
VOLUME /app/userconfig

COPY --from=0 /app/out ./

ENTRYPOINT ["dotnet", "Parser.dll"]
