FROM microsoft/dotnet:2-sdk

WORKDIR /app/Parser
VOLUME /app/Parser/calendars
VOLUME /app/Parser/eventfiles
VOLUME /app/Parser/userconfig

COPY CalendarBackendLib /app/CalendarBackendLib
COPY Parser/Parser.csproj ./
RUN dotnet restore

COPY Parser/ ./
RUN dotnet publish -c Release -o out
ENTRYPOINT ["dotnet", "out/Parser.dll"]
