FROM microsoft/dotnet:2-sdk

WORKDIR /app/Downloader
VOLUME /app/Downloader/additionalEvents
VOLUME /app/Downloader/eventfiles

COPY CalendarBackendLib /app/CalendarBackendLib
COPY Downloader/Downloader.csproj ./
RUN dotnet restore

COPY Downloader/ ./
RUN dotnet publish -c Release -o out
ENTRYPOINT ["dotnet", "out/Downloader.dll"]
