FROM microsoft/dotnet:2-sdk

COPY CalendarBackendLib /app/CalendarBackendLib

WORKDIR /app/Mensa
VOLUME /app/Mensa/meals

COPY Mensa/Mensa.csproj ./
RUN dotnet restore

COPY Mensa/ ./
RUN dotnet publish -c Release -o out
ENTRYPOINT ["dotnet", "out/Mensa.dll"]
